// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/curtly-variants/AcademicDesk.tsx": () => import("../components/mockups/curtly-variants/AcademicDesk.tsx"),
  "./components/mockups/curtly-variants/ChatTutor.tsx": () => import("../components/mockups/curtly-variants/ChatTutor.tsx"),
  "./components/mockups/curtly-variants/CommandWorkspace.tsx": () => import("../components/mockups/curtly-variants/CommandWorkspace.tsx"),
  "./components/mockups/curtly-variants/GuidedJourney.tsx": () => import("../components/mockups/curtly-variants/GuidedJourney.tsx")
};
